.pc
.TH doc-n-save.raku 1 2024-01-23
.SH Doc\-N\-Save 
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.RS 2n
.IP \(bu 2m
doc\-n\-save [#doc-n-save-1]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
In detail
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
doc\-n\-save [#doc-n-save-2]
.RE
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
doc\-n\-save create config [#doc-n-save-create-config]
.RE
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
doc\-n\-save prompt create config [#doc-n-save-prompt-create-config]
.RE
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
doc\-n\-save explicit [#doc-n-save-explicit]
.RE
.RE
.RE
.RS 2n
.IP \(bu 2m
mk\-raku\-dirs [#mk-raku-dirs]
.RE
.RS 2n
.IP \(bu 2m
release [#release]
.RE
.RS 2n
.IP \(bu 2m
release\-d [#release-d]
.RE
.SH "NAME"
Doc\-N\-Save 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.13
.SH "TITLE"
Doc\-N\-Save
.SH "SUBTITLE"
A collection of \fBRaku\fR programs for managing modules and apps in \fBRaku\fR, and do things like summit to zef etc\&.
.SH "COPYRIGHT"
GPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/App-Doc-N-Save/blob/main/LICENSE]

Top of Document [#table-of-contents]
.SH Introduction

A collection of \fBRaku\fR programs for managing modules and apps in \fBRaku\fR, and do things like summit to zef etc\&. 
.IP \(bu 2m
doc\-n\-save [#doc-n-save-1] a program for generating Documentation from pod files (files containing pod6 markup) and saving the result to git\&.
.IP \(bu 2m
mk\-raku\-dirs [#mk-raku-dirs] either create a full skeleton repository from a few simple arguments or make sure that an existing repository is complete\&. 
.IP \(bu 2m
release [#release] is a program to send a new release to \fBzef\fR via \fBfez\fR\&.
.IP \(bu 2m
release\-d [#release-d] is a program to send a new release to \fBzef\fR via \fBfez\fR this one solves a bug in \fBfez\fR\&.
.SS doc\-n\-save\&.raku
.SS doc\-n\-save 

.RS 4m
.EX
doc\-n\-save \-\-help
Usage:
  doc\-n\-save [\-c|\-\-comment=<Str>]
  doc\-n\-save create config <name> [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]
  doc\-n\-save prompt create config [<name>] [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]
  doc\-n\-save explicit <name> [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]


.EE
.RE
.P
\fBdoc\-n\-save\fR expects to be run from the root directory of the project\&.
.IP \(bu 2m
Where (in brief)
.RS 2n
.IP \(bu 2m
The first form \fBdoc\-n\-save [\-c|\-\-comment=<Str>]\fR expects a \fB\&.doc\-n\-save\&.json\fR file to exist in the root directory of the project which is where you run doc\-n\-save from\&. 
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
comment should be a string to override the comment in the \fB\&.doc\-n\-save\&.json\fR file or leave it out to leave that comment in\&.
.RE
.RE
.RS 2n
.IP \(bu 2m
the \fBdoc\-n\-save create config\fR creates a \fB\&.doc\-n\-save\&.json\fR file for the first form to use\&.
.RE
.RS 2n
.IP \(bu 2m
\fBdoc\-n\-save prompt create config\fR also creates a config file \fB\&.doc\-n\-save\&.json\fR but gives you a input\-menu that allows you to build the correct values a step at a time\&.
.RE
.RS 2n
.IP \(bu 2m
The \fBdoc\-n\-save explicit\fR form takes all the same arguments as the \fBdoc\-n\-save create config\fR form but does the create docs and save them to git without saving the args like the other\&.
.RE

Top of Document [#table-of-contents]
.SS doc\-n\-save

With no arguments \fBdoc\-n\-save\fR looks for a file called \fB\&.doc\-n\-save\&.json\fR and uses that to set the parameters to generate the docs and then save them to git i\&.e\&. commit and push to main/remote repo\&.

.RS 4m
.EX
doc\-n\-save  \-\-help
Usage:
  doc\-n\-save [\-c|\-\-comment=<Str>]


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS doc\-n\-save create config

Generates the \fB\&.doc\-n\-save\&.json\fR from the supplied arguments and any Environment\&.

.RS 4m
.EX
doc\-n\-save  \-\-help
Usage:
  doc\-n\-save create config <name> [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fBname\fR is the name of the primary pod file 
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBNB: can be an application file (i\&.e\&. ending in \fI\&.raku\fR), a Module (i\&.e\&. ending in \fI\&.rakumod\fR) or a doc file (i\&.e\&. ending in \fI\&.rakudoc\fR)\fR\&.
.RE
.RE
.RS 2n
.IP \(bu 2m
\fBadditional\-pod\-files\&.\&.\&.\fR A list of zero or more other pod files\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-l|\-\-lib=<Str>\fR The name of the library directory by default rakulib with a symbolic link of lib to alias it to that\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-b|\-\-bin=<Str>\fR The name of the bin directory, for executables within the library\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-e|\-\-exts=<Str>\fR An array of extensions to look for separated by \fB:\fR by default \fBrakumod:raku:rakudoc\fR these are the standard extensions so you probably should leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-d|\-\-docs=<Str>\fR The name of the documentation directory\&. 
.RE
.RS 2n
.IP \(bu 2m
\fB\-m|\-\-markdown\-path=<Str>\fR The path to the primary \fBmarkdown\fR file by default \fBREADME\&.md\fR, generally leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-o|\-\-only\-app\fR Set to true if this is a executable only package (i\&.e\&. no modules)\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-\-separate\-markdown\-files\fR Set to true if you want each \fBmarkdown\fR file to generate it's own \fBmarkdown\fR file, generally you don't want this, as \fBraku\&.land\fR currently will not carry the docs directory etc\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-c|\-\-comment=<Str>\fR Set to a comment you want to use for the git commit defaults to \fBusing doc\-n\-save\fR\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBdo\-n\-save actually uses a date time and the comment field as the commit comment, (i\&.e\&. \fI$comment $datetime\fR)\fR\&.
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
Where $comment is the comment you set, and $datetime is a full ISO 8601 timestamp notation, including nano seconds and timezone offset\&. (i\&.e\&. 2024\-02\-23T06:10:30\&.2387654+11:00)
.RE
.RE
.RE

Top of Document [#table-of-contents]
.SS doc\-n\-save prompt create config

Build the \fB\&.doc\-n\-save\&.json\fR file interactively using a menu system\&. 

.RS 4m
.EX
doc\-n\-save prompt create config \-\-help
Usage:
  doc\-n\-save prompt create config [<name>] [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fBname\fR is the name of the primary pod file 
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBNB: can be an application file (i\&.e\&. ending in \fI\&.raku\fR), a Module (i\&.e\&. ending in \fI\&.rakumod\fR) or a doc file (i\&.e\&. ending in \fI\&.rakudoc\fR)\fR\&.
.RE
.RE
.RS 2n
.IP \(bu 2m
\fBadditional\-pod\-files\&.\&.\&.\fR A list of zero or more other pod files\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-l|\-\-lib=<Str>\fR The name of the library directory by default rakulib with a symbolic link of lib to alias it to that\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-b|\-\-bin=<Str>\fR The name of the bin directory, for executables within the library\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-e|\-\-exts=<Str>\fR An array of extensions to look for separated by \fB:\fR by default \fBrakumod:raku:rakudoc\fR these are the standard extensions so you probably should leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-d|\-\-docs=<Str>\fR The name of the documentation directory\&. 
.RE
.RS 2n
.IP \(bu 2m
\fB\-m|\-\-markdown\-path=<Str>\fR The path to the primary \fBmarkdown\fR file by default \fBREADME\&.md\fR, generally leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-o|\-\-only\-app\fR Set to true if this is a executable only package (i\&.e\&. no modules)\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-\-separate\-markdown\-files\fR Set to true if you want each \fBmarkdown\fR file to generate it's own \fBmarkdown\fR file, generally you don't want this, as \fBraku\&.land\fR currently will not carry the docs directory etc\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-c|\-\-comment=<Str>\fR Set to a comment you want to use for the git commit defaults to \fBusing doc\-n\-save\fR\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBdo\-n\-save actually uses a date time and the comment field as the commit comment, (i\&.e\&. \fI$comment $datetime\fR)\fR\&.
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
Where $comment is the comment you set, and $datetime is a full ISO 8601 timestamp notation, including nano seconds and timezone offset\&. (i\&.e\&. 2024\-02\-23T06:10:30\&.2387654+11:00)
.RE
.RE
.RE

Top of Document [#table-of-contents]

.RS 4m
.EX
doc\-n\-save prompt create config doc\-n\-save mk\-raku\-dirs release release\-d

Configure Doc\-N\-Save
         0	name > doc\-n\-save   
         1	lib > rakulib       
         2	bin > bin           
         3	exts > rakumod, raku, rakudoc
         4	docs > docs         
         5	markdown\-path > README\&.md
         6	only\-app > False    
         7	separate\-markdown\-files > False
         8	comment > using doc\-n\-save
         9	additional\-pod\-files > mk\-raku\-dirs, release, release\-d
        10	cancel > cancel     
        11	OK > OK             
use cancel, bye, bye bye, quit, q, or 11 to quit or enter to accept the values as is
choose a candidate 0\&.\&.11 =:> ⌼


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS doc\-n\-save explicit

Define the docs etc explicitly and then commit to git etc\&.

.RS 4m
.EX
doc\-n\-save explicit  \-\-help
Usage:
  doc\-n\-save explicit <name> [<additional\-pod\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-e|\-\-exts=<Str>] [\-d|\-\-docs=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-o|\-\-only\-app] [\-\-separate\-markdown\-files] [\-c|\-\-comment=<Str>]


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fBname\fR is the name of the primary pod file 
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBNB: can be an application file (i\&.e\&. ending in \fI\&.raku\fR), a Module (i\&.e\&. ending in \fI\&.rakumod\fR) or a doc file (i\&.e\&. ending in \fI\&.rakudoc\fR)\fR\&.
.RE
.RE
.RS 2n
.IP \(bu 2m
\fBadditional\-pod\-files\&.\&.\&.\fR A list of zero or more other pod files\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-l|\-\-lib=<Str>\fR The name of the library directory by default rakulib with a symbolic link of lib to alias it to that\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-b|\-\-bin=<Str>\fR The name of the bin directory, for executables within the library\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-e|\-\-exts=<Str>\fR An array of extensions to look for separated by \fB:\fR by default \fBrakumod:raku:rakudoc\fR these are the standard extensions so you probably should leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-d|\-\-docs=<Str>\fR The name of the documentation directory\&. 
.RE
.RS 2n
.IP \(bu 2m
\fB\-m|\-\-markdown\-path=<Str>\fR The path to the primary \fBmarkdown\fR file by default \fBREADME\&.md\fR, generally leave this alone\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-o|\-\-only\-app\fR Set to true if this is a executable only package (i\&.e\&. no modules)\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-\-separate\-markdown\-files\fR Set to true if you want each \fBmarkdown\fR file to generate it's own \fBmarkdown\fR file, generally you don't want this, as \fBraku\&.land\fR currently will not carry the docs directory etc\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-c|\-\-comment=<Str>\fR Set to a comment you want to use for the git commit defaults to \fBusing doc\-n\-save\fR\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBdo\-n\-save actually uses a date time and the comment field as the commit comment, (i\&.e\&. \fI$comment $datetime\fR)\fR\&.
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
Where $comment is the comment you set, and $datetime is a full ISO 8601 timestamp notation, including nano seconds and timezone offset\&. (i\&.e\&. 2024\-02\-23T06:10:30\&.2387654+11:00)
.RE
.RE
.RE

Top of Document [#table-of-contents]
