.pc
.TH mk-raku-dirs.raku 1 2024-01-04
.SS Mk\-Raku\-Dirs\&.raku
.SS Mk\-Raku\-Dirs 

A \fBRaku\fR program for either create a full skeleton repository from a few simple arguments or make sure that an existing repository is complete\&. 

.RS 4m
.EX
mk\-raku\-dirs \-\-help
Usage:
  mk\-raku\-dirs empty <name> [<additional\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-d|\-\-docs=<Str>] [\-T|\-\-tags=<Str>] [\-p|\-\-depends=<Str>] [\-t|\-\-test=<Str>] [\-\-test\-depends=<Str>] [\-\-git\-dir=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-c|\-\-comment|\-\-git\-comment=<Str>] [\-a|\-\-application|\-\-app] [\-o|\-\-only\-app] [\-D|\-\-description=<Str>] [\-\-git\-url=<Str>] [\-u|\-\-git\-user=<Str>] [\-e|\-\-email=<Str>] [\-U|\-\-git\-username=<Str>] [\-\-zef\-auth=<Str>]
  mk\-raku\-dirs here <name> [<additional\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-d|\-\-docs=<Str>] [\-T|\-\-tags=<Str>] [\-p|\-\-depends=<Str>] [\-t|\-\-test=<Str>] [\-\-test\-depends=<Str>] [\-\-git\-dir=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-c|\-\-comment|\-\-git\-comment=<Str>] [\-a|\-\-application|\-\-app] [\-o|\-\-only\-app] [\-D|\-\-description=<Str>] [\-u|\-\-git\-user=<Str>] [\-e|\-\-email=<Str>] [\-U|\-\-git\-username=<Str>] [\-\-zef\-auth=<Str>]


.EE
.RE
.P
Top of Document [#table-of-contents]
