.pc
.TH mk-raku-dirs.raku 1 2024-01-03
.SH Mk\-Raku\-Dirs 
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.IP \(bu 2m
list\-by(…) [#list-by]
.RS 2n
.IP \(bu 2m
Examples: [#examples]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
A more complete example: [#a-more-complete-example]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
Another example: [#another-example]
.RE
.RE
.RS 2n
.RS 2n
.RS 2n
.IP \(bu 2m
An Example of the above code \fBlist\-editors\-backups(…)\fR at work: [#An-Example-of-the-above-code-list-editors-backups-at-work]
.RE
.RE
.RE
.IP \(bu 2m
The default callbacks [#the-default-callbacks]
.RS 2n
.IP \(bu 2m
The hash of hashes stuff [#the-hash-of-hashes-stuff]
.RE
.RS 2n
.IP \(bu 2m
The array of hashes stuff [#the-array-of-hashes-stuff]
.RE
.SH "NAME"
Display::Listings 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.0
.SH "TITLE"
Display::Listings
.SH "SUBTITLE"
A Raku module for displaying lines in a listing\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/Display-Listings/blob/main/LICENSE]

Top of Document [#table-of-contents]
.SH Introduction

A \fBRaku\fR program for generating docs and saving it's changes to git\&. 
.SS Primary MAIN 

.RS 4m
.EX
multi sub MAIN('empty', Str:D $name, Str:D :l(:$lib) is copy = 'rakulib', Str:D :b(:$bin) is copy = 'bin',
                     Str:D :d(:$docs) is copy = 'docs', Str:D :T(:$tags) = '',
                     Str:D :p(:$depends) = '', Str:D :t(:$test) = 't',
                     Str:D :$test\-depends = '', Str :$git\-dir is copy = Str,
                     Str:D :m(:$markdown\-path) is copy = 'README\&.md',
                     Str:D :c(:comment(:$git\-comment)) = 'first commit', 
                     Bool:D :a(:application(:$app)) is copy = False, 
                     Bool:D :o(:$only\-app) is copy = False, 
                     Str :D(:$description) is copy = Str, 
                     Str :$git\-url is copy = Str,
                     Str :u(:$git\-user) is copy = Str,
                     Str :e(:$email) is copy = Str,
                     Str :$zef\-auth is copy = Str,
                     *@additional\-files \-\-> Int:D) 


.EE
.RE
.P
Top of Document [#table-of-contents]
