.pc
.TH mk-raku-dirs.raku 1 2024-01-04
.SH Mk\-Raku\-Dirs 
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.IP \(bu 2m
mk\-raku\-dirs [#mk-raku-dirs-1]
.IP \(bu 2m
main README [/README.md]
.SH "NAME"
Display::Listings 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.2
.SH "TITLE"
Display::Listings
.SH "SUBTITLE"
A Raku module for displaying lines in a listing\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/App-Doc-N-Save/blob/main/LICENSE]

Top of Document [#table-of-contents]
.SH Introduction

A \fBRaku\fR program for either create a full skeleton repository from a few simple arguments or make sure that an existing repository is complete\&. 
.SS mk\-raku\-dirs 

.RS 4m
.EX
mk\-raku\-dirs \-\-help
Usage:
  mk\-raku\-dirs empty <name> [<additional\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-d|\-\-docs=<Str>] [\-T|\-\-tags=<Str>] [\-p|\-\-depends=<Str>] [\-t|\-\-test=<Str>] [\-\-test\-depends=<Str>] [\-\-git\-dir=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-c|\-\-comment|\-\-git\-comment=<Str>] [\-a|\-\-application|\-\-app] [\-o|\-\-only\-app] [\-D|\-\-description=<Str>] [\-\-git\-url=<Str>] [\-u|\-\-git\-user=<Str>] [\-e|\-\-email=<Str>] [\-U|\-\-git\-username=<Str>] [\-\-zef\-auth=<Str>]
  mk\-raku\-dirs here <name> [<additional\-files> \&.\&.\&.] [\-l|\-\-lib=<Str>] [\-b|\-\-bin=<Str>] [\-d|\-\-docs=<Str>] [\-T|\-\-tags=<Str>] [\-p|\-\-depends=<Str>] [\-t|\-\-test=<Str>] [\-\-test\-depends=<Str>] [\-\-git\-dir=<Str>] [\-m|\-\-markdown\-path=<Str>] [\-c|\-\-comment|\-\-git\-comment=<Str>] [\-a|\-\-application|\-\-app] [\-o|\-\-only\-app] [\-D|\-\-description=<Str>] [\-u|\-\-git\-user=<Str>] [\-e|\-\-email=<Str>] [\-U|\-\-git\-username=<Str>] [\-\-zef\-auth=<Str>]


.EE
.RE
.P
Top of Document [#table-of-contents]
