.pc
.TH release.raku 1 2024-01-04
.SS release\&.raku
.SS release

A \fBRaku\fR program to fez upload programs or modules to zef and update the the git repositories release tags\&. 

\fBNote: I found the original release\&.raku on the web somewhere in raku\&.land [https://raku.land/], if you are the originator please claim it so I can give credit\fR\&.

.RS 4m
.EX
release_d \-\-help
Usage:
  release_d


.EE
.RE
.P
Top of Document [#table-of-contents]
