.pc
.TH release-d.raku 1 2024-01-04
.SS release\-d\&.raku 
.SS release\-d 
.SS release_d 

A \fBRaku\fR program to fez upload programs or modules to zef and update the the git repositories release tags\&. 

\fBNote1: you will need a \fIarchive/\fR directory for this best put it in your \fI\&.gitignore\fR as those archieve files get too big\fR\&.

\fBNote2:\fR This uses git archive to get around a fez/zef update bug\&.

\fBNote3:\fR I found the original release\&.raku on the web somewhere in raku\&.land [https://raku.land/], if you are the originator please claim it so I can give credit\&.

.RS 4m
.EX
release\-d \-\-help
Usage:
  release\-d


.EE
.RE
.P
Top of Document [#table-of-contents]
